package com.trackme.ui.workout.session.notification

/**
 * Immutable view model for rendering workout notifications.
 */
data class WorkoutNotificationModel(
    val notificationState: WorkoutNotificationState,
    val sessionId: String,
    val workoutTitle: String,
    val statusLine: String,
    val subStatusLine: String,
    val currentExerciseName: String,
    val nextExerciseName: String,
    val muscleGroupLabel: String,
    val currentSetNumber: Int,
    val targetSets: Int,
    val targetReps: Int,
    val targetWeightKg: Float,
    val previousSetSummary: String,
    val completedSetsTotal: Int,
    val totalTargetSets: Int,
    val workoutProgressPercent: Int,
    val setProgressPercent: Int,
    val totalVolumeKg: Float,
    val elapsedFormatted: String,
    val restSecondsRemaining: Int,
    val restSecondsTotal: Int,
    val restProgressPercent: Int,
    val isRestUrgent: Boolean,
    val quickWeight: Float,
    val quickReps: Int,
    val statusIconRes: Int,
    val exerciseIconRes: Int,
    val showCollapsedStart: Boolean,
    val showCollapsedComplete: Boolean,
    val showCollapsedSkipRest: Boolean,
    val showRestPanel: Boolean,
    val showQuickLogPanel: Boolean,
    val pauseButtonLabel: String,
    val primaryActionLabel: String,
    val primaryAction: String,
    val displayPlan: NotificationDisplayPlan,
    val contextLine: String,
)
